baseURL = "https://Palaniappan12345.github.io/mlnotes/"
languageCode = "en-us"
title = "Palaniappan"
theme = "berbera"

pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
publishDir="docs"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
